export const MainnetNetworks = [
  {
    isMainnet: true,
    chainId: 42793,
    rpcUrls: ["https://node.mainnet.etherlink.com"],
    chainName: "Etherlink Mainnet",
    nativeCurrency: {
      name: "XTZ",
      symbol: "XTZ",
      decimals: 18,
    },
    blockExplorerUrls: ["https://etherlink.blockscout.com"],
  },
  {
    isMainnet: true,
    chainId: 1,
    rpcUrls: ["https://mainnet.infura.io/v3/"],
    chainName: "Ethereum Mainnet",
    nativeCurrency: {
      name: "MATIC",
      symbol: "MATIC",
      decimals: 18,
    },
    blockExplorerUrls: ["https://etherscan.io"],
  },
  {
    isMainnet: true,
    chainId: 137,
    rpcUrls: ["https://polygon.llamarpc.com"],
    chainName: "Polygon Mainnet",
    nativeCurrency: {
      name: "MATIC",
      symbol: "MATIC",
      decimals: 18,
    },
    blockExplorerUrls: ["https://polygonscan.com/"],
  },
  {
    isMainnet: true,
    chainId: 1101,
    rpcUrls: ["https://rpc.ankr.com/polygon_zkevm"],
    chainName: "Polygon zkEVM",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://zkevm.polygonscan.com"],
  },
  {
    isMainnet: true,
    chainId: 789,
    rpcUrls: ["https://rpc.patex.io/"],
    chainName: "Patex Network",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://patexscan.io/"],
  },
  {
    isMainnet: true,
    chainId: 1116,
    chainName: "Core Blockchain Mainnet",
    rpcUrls: ["https://rpc.coredao.org"],
    nativeCurrency: {
      name: "CORE",
      symbol: "CORE",
      decimals: 18,
    },
    blockExplorerUrls: ["https://scan.coredao.org"],
  },
];

export const TestnetNetworks = [
  // {
  //   chainId: 80001,
  //   rpcUrls: ["https://rpc-mumbai.maticvigil.com"],
  //   chainName: "Polygon Mumbai",
  //   nativeCurrency: {
  //     name: "MATIC",
  //     symbol: "MATIC",
  //     decimals: 18,
  //   },
  //   blockExplorerUrls: ["https://mumbai.polygonscan.com"],
  // },
  {
    chainId: 80002,
    rpcUrls: ["https://rpc-amoy.polygon.technology"],
    chainName: "Polygon Amoy",
    nativeCurrency: {
      name: "MATIC",
      symbol: "MATIC",
      decimals: 18,
    },
    blockExplorerUrls: ["https://amoy.polygonscan.com"],
  },
  {
    chainId: 1442,
    rpcUrls: ["https://api.zan.top/node/v1/polygonzkevm/testnet/public"],
    chainName: "Polygon zkEVM Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://explorer.public.zkevm-test.net"],
  },
  {
    chainId: 421613,
    rpcUrls: ["https://endpoints.omniatech.io/v1/arbitrum/goerli/public"],
    chainName: "Arbitrum Goerli",
    nativeCurrency: {
      name: "AGOR",
      symbol: "AGOR",
      decimals: 18,
    },
    blockExplorerUrls: ["https://goerli.arbiscan.io"],
  },
  {
    chainId: 421614,
    rpcUrls: ["https://endpoints.omniatech.io/v1/arbitrum/goerli/public"],
    chainName: "Arbitrum Sepolia",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://sepolia-explorer.arbitrum.io"],
  },
  {
    chainId: 420,
    rpcUrls: ["https://endpoints.omniatech.io/v1/op/goerli/public"],
    chainName: "Optimism Goerli",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://optimism-goerli.blockscout.com"],
  },
  {
    chainId: 84531,
    rpcUrls: ["https://base-goerli.diamondswap.org/rpc"],
    chainName: "Base Goerli Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://goerli.basescan.org"],
  },
  {
    chainId: 84532,
    rpcUrls: ["https://rpc.notadegen.com/base/sepolia"],
    chainName: "Base Sepolia Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://base-sepolia.blockscout.com"],
  },
  {
    chainId: 534351,
    rpcUrls: ["https://scroll-sepolia.blockpi.network/v1/rpc/public"],
    chainName: "Scroll Sepolia Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://sepolia.scrollscan.com"],
  },
  {
    chainId: 300,
    rpcUrls: ["https://zksync-era-sepolia.blockpi.network/v1/rpc/public"],
    chainName: "zkSync Sepolia Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://sepolia.explorer.zksync.io"],
  },
  {
    chainId: 999999999,
    rpcUrls: ["https://sepolia.rpc.zora.energy"],
    chainName: "Zora Sepolia Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://sepolia.explorer.zora.energy"],
  },
  {
    chainId: 128123,
    rpcUrls: ["https://node.ghostnet.etherlink.com"],
    chainName: "Etherlink Testnet",
    nativeCurrency: {
      name: "XTZ",
      symbol: "XTZ",
      decimals: 18,
    },
    blockExplorerUrls: ["https://testnet-explorer.etherlink.com"],
  },
  {
    chainId: 471100,
    rpcUrls: ["https://test-rpc.patex.io/"],
    chainName: "Patex Sepolia",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://testnet.patexscan.io/"],
  },
  {
    chainId: 59140,
    rpcUrls: ["https://linea-goerli.blockpi.network/v1/rpc/public"],
    chainName: "Linea Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    blockExplorerUrls: ["https://goerli.lineascan.build"],
  },
  {
    chainId: 80085,
    rpcUrls: ["https://artio.rpc.berachain.com"],
    chainName: "Berachain Artio",
    nativeCurrency: {
      name: "BERA",
      symbol: "BERA",
      decimals: 18,
    },
    blockExplorerUrls: ["https://artio.beratrail.io"],
  },
  {
    chainId: 8082,
    rpcUrls: ["https://sphinx.shardeum.org/"],
    chainName: "Shardeum Liberty 1.X",
    nativeCurrency: {
      name: "SHM",
      symbol: "SHM",
      decimals: 18,
    },
    blockExplorerUrls: ["https://explorer-sphinx.shardeum.org/"],
  },
  {
    chainId: 5001,
    rpcUrls: ["https://rpc.testnet.mantle.xyz"],
    chainName: "Mantle Testnet",
    nativeCurrency: {
      name: "MNT",
      symbol: "MNT",
      decimals: 18,
    },
    blockExplorerUrls: ["https://explorer.testnet.mantle.xyz"],
  },
  {
    chainId: 5003,
    chainName: "Mantle Sepolia Testnet",
    rpcUrls: ["https://rpc.sepolia.mantle.xyz"],
    nativeCurrency: {
      name: "MNT",
      symbol: "MNT",
      decimals: 18,
    },
    blockExplorerUrls: ["https://explorer.sepolia.mantle.xyz"],
  },
  {
    chainId: 3441005,
    chainName: "Manta Pacific Testnet",
    rpcUrls: ["https://manta-testnet.calderachain.xyz/http"],
    nativeCurrency: {
      name: "MANTA",
      symbol: "MANTA",
      decimals: 18,
    },
    blockExplorerUrls: ["https://manta-testnet.calderaexplorer.xyz"],
  },
  {
    chainId: 1115,
    chainName: "Core Blockchain Testnet",
    rpcUrls: ["https://rpc.test.btcs.network"],
    nativeCurrency: {
      name: "tCORE",
      symbol: "tCORE",
      decimals: 18,
    },
    blockExplorerUrls: ["https://scan.test.btcs.network"],
  },
];
